/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package techciti;

/**
 *
 * @author jains
 */
import javax.swing.JOptionPane;
import java.sql.*;
public class Loginpage extends javax.swing.JFrame {
          
    Connection conn = conn = MyConnection.getConnection();
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    public Loginpage() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Headerpane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bodypane = new javax.swing.JPanel();
        jLabelpass = new javax.swing.JLabel();
        jLabeluname = new javax.swing.JLabel();
        jTextFielduname = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButtonlogin = new javax.swing.JButton();
        jLabelforgotpasswd = new javax.swing.JLabel();
        jLabelnewuser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Headerpane.setBackground(new java.awt.Color(95, 158, 160));
        Headerpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LogIn Page");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("-");

        org.jdesktop.layout.GroupLayout HeaderpaneLayout = new org.jdesktop.layout.GroupLayout(Headerpane);
        Headerpane.setLayout(HeaderpaneLayout);
        HeaderpaneLayout.setHorizontalGroup(
            HeaderpaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, HeaderpaneLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(81, 81, 81)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderpaneLayout.setVerticalGroup(
            HeaderpaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(HeaderpaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(HeaderpaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, HeaderpaneLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .addContainerGap())
        );

        Bodypane.setBackground(new java.awt.Color(72, 61, 139));

        jLabelpass.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelpass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpass.setText("Password :");

        jLabeluname.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabeluname.setForeground(new java.awt.Color(255, 255, 255));
        jLabeluname.setText("Username :");

        jTextFielduname.setBackground(new java.awt.Color(204, 204, 204));
        jTextFielduname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFielduname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        jPasswordField.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        jButtonlogin.setBackground(new java.awt.Color(153, 153, 153));
        jButtonlogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonlogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonlogin.setText("LogIn");
        jButtonlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonloginMouseClicked(evt);
            }
        });

        jLabelforgotpasswd.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabelforgotpasswd.setForeground(new java.awt.Color(204, 0, 51));
        jLabelforgotpasswd.setText("Forgot Password?");
        jLabelforgotpasswd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelforgotpasswdMouseClicked(evt);
            }
        });

        jLabelnewuser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelnewuser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnewuser.setText("New user? Sign in");
        jLabelnewuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnewuserMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout BodypaneLayout = new org.jdesktop.layout.GroupLayout(Bodypane);
        Bodypane.setLayout(BodypaneLayout);
        BodypaneLayout.setHorizontalGroup(
            BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BodypaneLayout.createSequentialGroup()
                .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(BodypaneLayout.createSequentialGroup()
                        .add(131, 131, 131)
                        .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabeluname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabelpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(34, 34, 34)
                        .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFielduname)
                            .add(jPasswordField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                    .add(BodypaneLayout.createSequentialGroup()
                        .add(220, 220, 220)
                        .add(jButtonlogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabelforgotpasswd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(BodypaneLayout.createSequentialGroup()
                        .add(191, 191, 191)
                        .add(jLabelnewuser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        BodypaneLayout.setVerticalGroup(
            BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(BodypaneLayout.createSequentialGroup()
                .add(104, 104, 104)
                .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabeluname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFielduname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelpass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPasswordField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(29, 29, 29)
                .add(BodypaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonlogin)
                    .add(jLabelforgotpasswd))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabelnewuser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Headerpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(Bodypane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(Headerpane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Bodypane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonloginMouseClicked
        String uname = jTextFielduname.getText();
        String pass = String.valueOf(jPasswordField.getPassword());
        
        if (uname.equalsIgnoreCase("")){
         JOptionPane.showMessageDialog(null, "Username field is empty");
                 }
        else if (pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Password field is empty");
        }
        else
        {
            String query = "SELECT * FROM `user` WHERE `uname`=? AND `pass`=?";
           try
           {
               ps = conn.prepareStatement(query);
               ps.setString(1,uname);
               ps.setString(2,pass);
               rs = ps.executeQuery();
            
            if (rs.next())
            {
                String name = rs.getString(3); 
                String des = rs.getString(4);   
                
                 JOptionPane.showMessageDialog(null,"Login Successful");  
                 //Loginpage.dispose();
                 if(des.equals("Employee"))
                 {
                  Dashboardemp ds1 = new Dashboardemp(name,des);
                  ds1.setVisible(true);
                  ds1.pack();
                  ds1.setLocationRelativeTo(null);
                  this.dispose();
                
                   
                 }
                 else
                 {
                  Dashboard ds = new Dashboard(name,des);
                  ds.setVisible(true);
                  ds.pack();
                  ds.setLocationRelativeTo(null);
                  this.dispose();
                 
                 
                 }
            }
            else
            {     JOptionPane.showMessageDialog(null, "Login failed");  
                  jTextFielduname.setText("");
                  jPasswordField.setText("");
            } 
           }
           catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null, ex);  
                  }   
            
        }
    }//GEN-LAST:event_jButtonloginMouseClicked

    private void jLabelforgotpasswdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelforgotpasswdMouseClicked
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverPassword().setVisible(true);
               
            }
        });    
           this.dispose();// TODO
    }//GEN-LAST:event_jLabelforgotpasswdMouseClicked

    private void jLabelnewuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnewuserMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
               
            }
        });    
           this.dispose();// TODO// TODO add your handling code here:
    }//GEN-LAST:event_jLabelnewuserMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
           System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bodypane;
    private javax.swing.JPanel Headerpane;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelforgotpasswd;
    private javax.swing.JLabel jLabelnewuser;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabeluname;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFielduname;
    // End of variables declaration//GEN-END:variables

}
